from __future__ import annotations

import argparse
from datetime import datetime
import json
import os
from pathlib import Path
import shlex
import secrets
import statistics
import subprocess
import sys
import time
from typing import Any
import urllib.error
import urllib.request

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

os.environ.setdefault("BACKTEST_API_BASES", "http://dummy:10001")
from backtest_hub_cli.cli import load_strategy_bundle

try:
    from scripts.warmup_cycle_harness import MODES
except ImportError:  # pragma: no cover - direct script execution path
    from warmup_cycle_harness import MODES


DEFAULT_POLL_SECONDS = 15.0
DEFAULT_SKIP_INITIAL_CHUNKS = 10
TERMINAL_STATUSES = {"succeeded", "failed", "cancelled", "killed", "terminated", "stopped"}


def _app_module():
    import app

    return app


def _utc_timestamp_id() -> str:
    return time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())


def _parse_iso8601_loose(value: str) -> datetime:
    normalized = value.strip()
    if normalized.endswith("Z"):
        normalized = normalized[:-1] + "+00:00"
    if "." not in normalized:
        return datetime.fromisoformat(normalized)
    main, suffix = normalized.split(".", 1)
    if "+" in suffix:
        fraction, offset = suffix.split("+", 1)
        offset = "+" + offset
    elif "-" in suffix[1:]:
        fraction, offset = suffix.rsplit("-", 1)
        offset = "-" + offset
    else:
        fraction, offset = suffix, ""
    trimmed = fraction[:6].ljust(6, "0")
    return datetime.fromisoformat(f"{main}.{trimmed}{offset}")


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Submit a warmup-cycle harness directly to one worker, run modes in serial, "
            "optionally reset worker cache between runs, and record stable replay metrics."
        )
    )
    parser.add_argument("--harness-dir", required=True, help="Harness root generated by warmup_cycle_harness.py")
    parser.add_argument("--worker-base-url", required=True, help="Pinned worker base URL, e.g. http://100.65.27.118:10001")
    parser.add_argument("--results-dir", required=True, help="Directory where run artifacts and summaries are written")
    parser.add_argument(
        "--modes",
        default=",".join(mode.name for mode in MODES),
        help="Comma-separated mode order to run serially",
    )
    parser.add_argument(
        "--poll-seconds",
        type=float,
        default=DEFAULT_POLL_SECONDS,
        help="Progress poll interval in seconds",
    )
    parser.add_argument(
        "--skip-initial-chunks",
        type=int,
        default=DEFAULT_SKIP_INITIAL_CHUNKS,
        help="Ignore chunk probes at or below this index when computing stable replay metrics",
    )
    parser.add_argument(
        "--cache-stats-ssh-target",
        default=None,
        help=(
            "If set, sample the worker-local JuiceFS cache dir over ssh on each poll. "
            "Defaults to --reset-ssh-target when omitted and a reset target is provided."
        ),
    )
    parser.add_argument(
        "--reset-ssh-target",
        default=None,
        help="If set, run cache reset commands over ssh before each mode, e.g. root@neo-256gb",
    )
    parser.add_argument(
        "--cache-dir",
        default="/hdd16/jfscache",
        help="Worker-local JuiceFS cache directory to clear before each mode",
    )
    parser.add_argument(
        "--drop-page-cache",
        action="store_true",
        help="Also run sync && echo 3 > /proc/sys/vm/drop_caches after clearing JuiceFS cache",
    )
    parser.add_argument(
        "--require-idle-worker",
        action="store_true",
        help="Fail if the pinned worker has any active runs before reset or submit",
    )
    parser.add_argument(
        "--min-stable-progress-samples",
        type=int,
        default=None,
        help=(
            "If set, kill the run once this many heartbeat-derived stable replay "
            "samples have been collected beyond --skip-initial-chunks"
        ),
    )
    return parser.parse_args(argv)


def _normalize_join(base_url: str, path: str) -> str:
    return f"{base_url.rstrip('/')}/{path.lstrip('/')}"


def _read_json(url: str, *, timeout: float = 30.0, headers: dict[str, str] | None = None) -> dict[str, Any]:
    request = urllib.request.Request(url, headers=headers or {}, method="GET")
    with urllib.request.urlopen(request, timeout=timeout) as response:
        payload = json.loads(response.read().decode("utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"invalid JSON payload from {url}")
    return payload


def _read_text(url: str, *, timeout: float = 60.0, headers: dict[str, str] | None = None) -> str:
    request = urllib.request.Request(url, headers=headers or {}, method="GET")
    with urllib.request.urlopen(request, timeout=timeout) as response:
        return response.read().decode("utf-8", errors="replace")


def _post_json(url: str, *, timeout: float = 30.0, headers: dict[str, str] | None = None) -> dict[str, Any]:
    request = urllib.request.Request(url, data=b"", headers=headers or {}, method="POST")
    with urllib.request.urlopen(request, timeout=timeout) as response:
        payload = json.loads(response.read().decode("utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"invalid JSON payload from {url}")
    return payload


def _worker_runs(base_url: str) -> dict[str, Any]:
    return _read_json(_normalize_join(base_url, "/v1/runs"), headers=_app_module().backtest_headers())


def _worker_status(base_url: str, backtest_id: str) -> dict[str, Any]:
    return _read_json(
        _normalize_join(base_url, f"/v1/runs/backtest/{backtest_id}"),
        headers=_app_module().backtest_headers(),
    )


def _worker_progress(base_url: str, backtest_id: str) -> dict[str, Any]:
    return _read_json(
        _normalize_join(base_url, f"/v1/runs/backtest/{backtest_id}/progress"),
        headers=_app_module().backtest_headers(),
    )


def _worker_logs(base_url: str, backtest_id: str) -> str:
    return _read_text(
        _normalize_join(base_url, f"/v1/runs/backtest/{backtest_id}/logs/download"),
        headers=_app_module().backtest_headers(),
    )


def _worker_kill(base_url: str, backtest_id: str) -> dict[str, Any]:
    return _post_json(
        _normalize_join(base_url, f"/v1/runs/backtest/{backtest_id}/kill"),
        headers=_app_module().backtest_headers(),
    )


def _active_run_count(base_url: str) -> int:
    payload = _worker_runs(base_url)
    runs = payload.get("runs")
    if not isinstance(runs, list):
        raise ValueError("worker /v1/runs payload missing runs list")
    active = [run for run in runs if isinstance(run, dict) and run.get("status") in {"queued", "submitted", "running"}]
    return len(active)


def _reset_worker_cache(
    *,
    ssh_target: str,
    cache_dir: str,
    drop_page_cache: bool,
) -> dict[str, Any]:
    lines = [
        "set -euo pipefail",
        f'if [ -d "{cache_dir}" ]; then find "{cache_dir}" -mindepth 1 -maxdepth 1 -exec rm -rf -- {{}} +; fi',
        "sync",
    ]
    if drop_page_cache:
        lines.append('echo 3 > /proc/sys/vm/drop_caches')
    command = " && ".join(lines)
    completed = subprocess.run(
        ["ssh", ssh_target, command],
        check=True,
        capture_output=True,
        text=True,
    )
    return {
        "ssh_target": ssh_target,
        "cache_dir": cache_dir,
        "drop_page_cache": drop_page_cache,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
        "return_code": completed.returncode,
    }


def _sample_worker_cache_stats(
    *,
    ssh_target: str,
    cache_dir: str,
) -> dict[str, Any]:
    sampled_at = _utc_timestamp_id()
    started_at = time.perf_counter()
    quoted_cache_dir = shlex.quote(cache_dir)
    command = " && ".join(
        [
            "set -euo pipefail",
            (
                f"if [ -d {quoted_cache_dir} ]; then "
                f"exists=1; bytes=$(du -sb {quoted_cache_dir} | cut -f1); "
                "else exists=0; bytes=0; fi"
            ),
            "printf '%s\\t%s\\n' \"$exists\" \"$bytes\"",
        ]
    )
    try:
        completed = subprocess.run(
            ["ssh", ssh_target, command],
            check=True,
            capture_output=True,
            text=True,
        )
        line = completed.stdout.strip().splitlines()[-1]
        exists_raw, bytes_raw = line.split("\t", 1)
        return {
            "ssh_target": ssh_target,
            "cache_dir": cache_dir,
            "sampled_at": sampled_at,
            "duration_ms": round((time.perf_counter() - started_at) * 1000, 2),
            "exists": bool(int(exists_raw)),
            "bytes": int(bytes_raw),
            "error": None,
        }
    except Exception as exc:
        return {
            "ssh_target": ssh_target,
            "cache_dir": cache_dir,
            "sampled_at": sampled_at,
            "duration_ms": round((time.perf_counter() - started_at) * 1000, 2),
            "exists": None,
            "bytes": None,
            "error": repr(exc),
        }


def _mode_order(raw: str) -> list[str]:
    known = {mode.name for mode in MODES}
    parsed = [item.strip() for item in raw.split(",") if item.strip()]
    if not parsed:
        raise ValueError("at least one mode is required")
    unknown = [item for item in parsed if item not in known]
    if unknown:
        raise ValueError(f"unknown modes: {unknown}")
    return parsed


def _make_backtest_id(mode: str) -> str:
    return f"{_utc_timestamp_id()}_{mode}_{secrets.token_hex(8)}"


def _load_submission_assets(harness_dir: Path, mode: str, backtest_id: str) -> tuple[dict[str, Any], str, bytes, bytes, bytes]:
    mode_dir = harness_dir / mode
    bundle_path = harness_dir / "bundle" / "strategies-harness.zip"
    run_spec_path = mode_dir / "run_spec.json"
    if not mode_dir.is_dir():
        raise FileNotFoundError(f"mode directory missing: {mode_dir}")
    if not run_spec_path.is_file():
        raise FileNotFoundError(f"run_spec.json missing: {run_spec_path}")
    if not bundle_path.is_file():
        raise FileNotFoundError(f"strategy bundle missing: {bundle_path}")

    run_spec = json.loads(run_spec_path.read_text(encoding="utf-8"))
    if not isinstance(run_spec, dict):
        raise ValueError(f"run_spec must be a JSON object: {run_spec_path}")
    bundle_name, bundle_bytes = load_strategy_bundle(bundle_path)
    run_spec["backtest_id"] = backtest_id
    run_spec["strategy_bundle"] = bundle_name
    app_module = _app_module()
    runner_bytes = app_module.RUNNER_PATH.read_bytes()
    runner_support_bundle_bytes = app_module.build_runner_support_bundle_bytes()
    run_spec_bytes = (json.dumps(run_spec, ensure_ascii=True, indent=2) + "\n").encode("utf-8")
    return run_spec, bundle_name, bundle_bytes, runner_bytes, runner_support_bundle_bytes


def _percentile(values: list[float], fraction: float) -> float | None:
    if not values:
        return None
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    position = fraction * (len(ordered) - 1)
    lower = int(position)
    upper = min(lower + 1, len(ordered) - 1)
    weight = position - lower
    return ordered[lower] * (1.0 - weight) + ordered[upper] * weight


def _progress_point(row: dict[str, Any] | None) -> dict[str, Any] | None:
    if not isinstance(row, dict):
        return None
    progress = row.get("progress")
    if not isinstance(progress, dict):
        return None
    probe = progress.get("streaming_probe")
    if not isinstance(probe, dict):
        probe = {}
    summary = progress.get("streaming_summary")
    if not isinstance(summary, dict):
        summary = {}
    cache_stats = row.get("cache_stats")
    if not isinstance(cache_stats, dict):
        cache_stats = {}
    last_progress_at = progress.get("last_progress_at")
    simulated_time = progress.get("simulated_time")
    if not isinstance(last_progress_at, str) or not isinstance(simulated_time, str):
        return None
    try:
        wall_time = _parse_iso8601_loose(last_progress_at)
        sim_time = _parse_iso8601_loose(simulated_time)
    except Exception:
        return None
    chunk_index = probe.get("chunk_index")
    return {
        "wall_time": wall_time,
        "sim_time": sim_time,
        "chunk_index": int(chunk_index) if isinstance(chunk_index, int) else None,
        "events_seen": int(summary["events_seen"]) if isinstance(summary.get("events_seen"), int) else None,
        "file_touch_files_touched": (
            int(summary["file_touch_files_touched"])
            if isinstance(summary.get("file_touch_files_touched"), int)
            else None
        ),
        "file_touch_bytes_touched": (
            int(summary["file_touch_bytes_touched"])
            if isinstance(summary.get("file_touch_bytes_touched"), int)
            else None
        ),
        "file_touch_files_total": (
            int(summary["file_touch_files_total"])
            if isinstance(summary.get("file_touch_files_total"), int)
            else None
        ),
        "file_touch_bytes_total": (
            int(summary["file_touch_bytes_total"])
            if isinstance(summary.get("file_touch_bytes_total"), int)
            else None
        ),
        "cache_dir_bytes": (
            int(cache_stats["bytes"])
            if isinstance(cache_stats.get("bytes"), int)
            else None
        ),
    }


def _progress_delta_samples(progress_rows: list[dict[str, Any]], *, skip_initial_chunks: int) -> list[dict[str, float]]:
    samples: list[dict[str, float]] = []
    previous_point: dict[str, Any] | None = None
    for row in progress_rows:
        point = _progress_point(row)
        if point is None:
            continue
        if previous_point is not None:
            sample = _progress_delta_sample(previous_point, point, skip_initial_chunks=skip_initial_chunks)
            if sample is not None:
                samples.append(sample)
        previous_point = point
    return samples


def _progress_delta_sample(
    previous_point: dict[str, Any],
    point: dict[str, Any],
    *,
    skip_initial_chunks: int,
) -> dict[str, float] | None:
    chunk_index = point.get("chunk_index")
    if not isinstance(chunk_index, int) or chunk_index <= skip_initial_chunks:
        return None
    wall_delta = (point["wall_time"] - previous_point["wall_time"]).total_seconds()
    sim_delta = (point["sim_time"] - previous_point["sim_time"]).total_seconds()
    prev_events = previous_point.get("events_seen")
    curr_events = point.get("events_seen")
    if (
        wall_delta <= 0
        or sim_delta < 0
        or not isinstance(prev_events, int)
        or not isinstance(curr_events, int)
        or curr_events < prev_events
    ):
        return None
    chunk_delta = None
    prev_chunk_index = previous_point.get("chunk_index")
    if isinstance(prev_chunk_index, int):
        chunk_delta = float(chunk_index - prev_chunk_index)
    return {
        "events_per_second": float(curr_events - prev_events) / wall_delta,
        "simulated_seconds_per_wall_second": sim_delta / wall_delta,
        "chunks_per_second": chunk_delta / wall_delta if chunk_delta is not None else 0.0,
        "new_files_touched": (
            point["file_touch_files_touched"] - previous_point["file_touch_files_touched"]
            if isinstance(previous_point.get("file_touch_files_touched"), int)
            and isinstance(point.get("file_touch_files_touched"), int)
            and point["file_touch_files_touched"] >= previous_point["file_touch_files_touched"]
            else None
        ),
        "new_bytes_touched": (
            point["file_touch_bytes_touched"] - previous_point["file_touch_bytes_touched"]
            if isinstance(previous_point.get("file_touch_bytes_touched"), int)
            and isinstance(point.get("file_touch_bytes_touched"), int)
            and point["file_touch_bytes_touched"] >= previous_point["file_touch_bytes_touched"]
            else None
        ),
        "cache_dir_bytes_growth": (
            point["cache_dir_bytes"] - previous_point["cache_dir_bytes"]
            if isinstance(previous_point.get("cache_dir_bytes"), int)
            and isinstance(point.get("cache_dir_bytes"), int)
            and point["cache_dir_bytes"] >= previous_point["cache_dir_bytes"]
            else None
        ),
    }


def _collect_unique_chunk_probes(progress_rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    probes: list[dict[str, Any]] = []
    seen: set[tuple[int, str]] = set()
    for row in progress_rows:
        progress = row.get("progress")
        if not isinstance(progress, dict):
            continue
        probe = progress.get("streaming_probe")
        if not isinstance(probe, dict):
            continue
        chunk_index = probe.get("chunk_index")
        updated_at = probe.get("updated_at")
        if not isinstance(chunk_index, int) or not isinstance(updated_at, str):
            continue
        key = (chunk_index, updated_at)
        if key in seen:
            continue
        seen.add(key)
        probes.append(probe)
    probes.sort(key=lambda item: (int(item["chunk_index"]), str(item["updated_at"])))
    return probes


def summarize_progress_rows(
    progress_rows: list[dict[str, Any]],
    *,
    skip_initial_chunks: int,
) -> dict[str, Any]:
    progress_points = [
        point
        for row in progress_rows
        if (point := _progress_point(row)) is not None
    ]
    last_progress_point = progress_points[-1] if progress_points else None
    probes = _collect_unique_chunk_probes(progress_rows)
    stable = [
        probe
        for probe in probes
        if int(probe.get("chunk_index", -1)) > skip_initial_chunks
    ]
    chunk_wall_ms = [
        float(probe["chunk_wall_ms"])
        for probe in stable
        if isinstance(probe.get("chunk_wall_ms"), (int, float))
    ]
    events_per_second = [
        float(probe["events_per_second"])
        for probe in stable
        if isinstance(probe.get("events_per_second"), (int, float))
    ]
    sim_per_wall = [
        float(probe["simulated_seconds_per_wall_second"])
        for probe in stable
        if isinstance(probe.get("simulated_seconds_per_wall_second"), (int, float))
    ]
    progress_deltas = _progress_delta_samples(progress_rows, skip_initial_chunks=skip_initial_chunks)
    progress_events_per_second = [sample["events_per_second"] for sample in progress_deltas]
    progress_sim_per_wall = [sample["simulated_seconds_per_wall_second"] for sample in progress_deltas]
    progress_chunks_per_second = [sample["chunks_per_second"] for sample in progress_deltas]
    progress_new_files_touched = [
        int(sample["new_files_touched"])
        for sample in progress_deltas
        if isinstance(sample.get("new_files_touched"), (int, float))
    ]
    progress_new_bytes_touched = [
        int(sample["new_bytes_touched"])
        for sample in progress_deltas
        if isinstance(sample.get("new_bytes_touched"), (int, float))
    ]
    progress_cache_dir_bytes_growth = [
        int(sample["cache_dir_bytes_growth"])
        for sample in progress_deltas
        if isinstance(sample.get("cache_dir_bytes_growth"), (int, float))
    ]
    return {
        "unique_chunk_probe_count": len(probes),
        "stable_chunk_probe_count": len(stable),
        "skip_initial_chunks": skip_initial_chunks,
        "last_chunk_index": probes[-1]["chunk_index"] if probes else None,
        "stable_chunk_wall_ms_median": statistics.median(chunk_wall_ms) if chunk_wall_ms else None,
        "stable_chunk_wall_ms_p90": _percentile(chunk_wall_ms, 0.9),
        "stable_events_per_second_median": statistics.median(events_per_second) if events_per_second else None,
        "stable_events_per_second_p90": _percentile(events_per_second, 0.9),
        "stable_simulated_seconds_per_wall_second_median": statistics.median(sim_per_wall) if sim_per_wall else None,
        "stable_simulated_seconds_per_wall_second_p90": _percentile(sim_per_wall, 0.9),
        "progress_delta_sample_count": len(progress_deltas),
        "progress_events_per_second_median": statistics.median(progress_events_per_second) if progress_events_per_second else None,
        "progress_events_per_second_p90": _percentile(progress_events_per_second, 0.9),
        "progress_simulated_seconds_per_wall_second_median": statistics.median(progress_sim_per_wall) if progress_sim_per_wall else None,
        "progress_simulated_seconds_per_wall_second_p90": _percentile(progress_sim_per_wall, 0.9),
        "progress_chunks_per_second_median": statistics.median(progress_chunks_per_second) if progress_chunks_per_second else None,
        "progress_file_touch_delta_sample_count": len(progress_new_files_touched),
        "progress_new_files_touched_total": sum(progress_new_files_touched) if progress_new_files_touched else None,
        "progress_new_files_touched_median": statistics.median(progress_new_files_touched) if progress_new_files_touched else None,
        "progress_new_files_touched_p90": _percentile(progress_new_files_touched, 0.9),
        "progress_new_bytes_touched_total": sum(progress_new_bytes_touched) if progress_new_bytes_touched else None,
        "progress_new_bytes_touched_median": statistics.median(progress_new_bytes_touched) if progress_new_bytes_touched else None,
        "progress_new_bytes_touched_p90": _percentile(progress_new_bytes_touched, 0.9),
        "progress_file_touch_active_ratio": (
            sum(1 for value in progress_new_files_touched if value > 0) / len(progress_new_files_touched)
            if progress_new_files_touched
            else None
        ),
        "progress_cache_dir_bytes_growth_sample_count": len(progress_cache_dir_bytes_growth),
        "progress_cache_dir_bytes_growth_total": (
            sum(progress_cache_dir_bytes_growth) if progress_cache_dir_bytes_growth else None
        ),
        "progress_cache_dir_bytes_growth_median": (
            statistics.median(progress_cache_dir_bytes_growth)
            if progress_cache_dir_bytes_growth
            else None
        ),
        "progress_cache_dir_bytes_growth_p90": _percentile(progress_cache_dir_bytes_growth, 0.9),
        "progress_cache_dir_growth_active_ratio": (
            sum(1 for value in progress_cache_dir_bytes_growth if value > 0)
            / len(progress_cache_dir_bytes_growth)
            if progress_cache_dir_bytes_growth
            else None
        ),
        "final_cache_dir_bytes": (
            last_progress_point.get("cache_dir_bytes") if last_progress_point is not None else None
        ),
        "final_file_touch_files_total": last_progress_point.get("file_touch_files_total") if last_progress_point is not None else None,
        "final_file_touch_bytes_total": last_progress_point.get("file_touch_bytes_total") if last_progress_point is not None else None,
        "final_file_touch_files_touched": last_progress_point.get("file_touch_files_touched") if last_progress_point is not None else None,
        "final_file_touch_bytes_touched": last_progress_point.get("file_touch_bytes_touched") if last_progress_point is not None else None,
    }


def _extract_warmup_lines(log_text: str) -> list[str]:
    return [line for line in log_text.splitlines() if "warmup cache:" in line]


def _submit_to_worker(
    *,
    worker_base_url: str,
    backtest_id: str,
    run_spec_bytes: bytes,
    bundle_name: str,
    bundle_bytes: bytes,
    runner_bytes: bytes,
    runner_support_bundle_bytes: bytes,
) -> str:
    app_module = _app_module()
    return app_module.submit_to_backtest(
        base_url=worker_base_url,
        backtest_id=backtest_id,
        run_spec_bytes=run_spec_bytes,
        strategy_filename=None,
        strategy_bytes=None,
        bundle_filename=bundle_name,
        bundle_bytes=bundle_bytes,
        runner_bytes=runner_bytes,
        runner_support_bundle_filename=app_module.RUNNER_SUPPORT_BUNDLE_FILENAME,
        runner_support_bundle_bytes=runner_support_bundle_bytes,
    )


def _poll_until_complete(
    *,
    worker_base_url: str,
    backtest_id: str,
    poll_seconds: float,
    progress_log_path: Path,
    skip_initial_chunks: int,
    min_stable_progress_samples: int | None,
    cache_stats_ssh_target: str | None,
    cache_dir: str,
) -> tuple[dict[str, Any], dict[str, Any], list[dict[str, Any]], dict[str, Any] | None]:
    rows: list[dict[str, Any]] = []
    last_report_monotonic = 0.0
    previous_point: dict[str, Any] | None = None
    stable_progress_sample_count = 0
    stop_rule_summary: dict[str, Any] | None = None
    kill_requested = False
    with progress_log_path.open("w", encoding="utf-8") as handle:
        while True:
            polled_at = _utc_timestamp_id()
            status_payload = _worker_status(worker_base_url, backtest_id)
            try:
                progress_payload = _worker_progress(worker_base_url, backtest_id)
            except urllib.error.HTTPError as exc:
                if exc.code != 404:
                    raise
                progress_payload = {"backtest_id": backtest_id, "progress": None}
            cache_stats = (
                _sample_worker_cache_stats(
                    ssh_target=cache_stats_ssh_target,
                    cache_dir=cache_dir,
                )
                if cache_stats_ssh_target
                else None
            )
            row = {
                "polled_at": polled_at,
                "status": status_payload,
                "progress": progress_payload.get("progress"),
                "cache_stats": cache_stats,
            }
            handle.write(json.dumps(row, ensure_ascii=True) + "\n")
            handle.flush()
            rows.append(row)
            status = status_payload.get("status")
            now_monotonic = time.monotonic()
            progress = row.get("progress")
            if not isinstance(progress, dict):
                progress = {}
            probe = progress.get("streaming_probe")
            if not isinstance(probe, dict):
                probe = {}
            point = _progress_point(row)
            progress_events_per_second = None
            progress_simulated_seconds_per_wall_second = None
            progress_cache_dir_bytes_growth = None
            if point is not None and previous_point is not None:
                sample = _progress_delta_sample(previous_point, point, skip_initial_chunks=skip_initial_chunks)
                if sample is not None:
                    stable_progress_sample_count += 1
                    progress_events_per_second = round(sample["events_per_second"], 6)
                    progress_simulated_seconds_per_wall_second = round(
                        sample["simulated_seconds_per_wall_second"],
                        6,
                    )
                    if isinstance(sample.get("cache_dir_bytes_growth"), (int, float)):
                        progress_cache_dir_bytes_growth = int(sample["cache_dir_bytes_growth"])
            if (
                not last_report_monotonic
                or (now_monotonic - last_report_monotonic) >= 60.0
                or (isinstance(status, str) and status in TERMINAL_STATUSES)
            ):
                print(
                    json.dumps(
                        {
                            "event": "poll",
                            "backtest_id": backtest_id,
                            "status": status,
                            "phase": progress.get("phase"),
                            "chunk_index": probe.get("chunk_index"),
                            "stable_progress_sample_count": stable_progress_sample_count,
                            "events_per_second": probe.get("events_per_second"),
                            "simulated_seconds_per_wall_second": probe.get("simulated_seconds_per_wall_second"),
                            "progress_events_per_second": progress_events_per_second,
                            "progress_simulated_seconds_per_wall_second": progress_simulated_seconds_per_wall_second,
                            "cache_dir_bytes": (
                                cache_stats.get("bytes")
                                if isinstance(cache_stats, dict)
                                else None
                            ),
                            "progress_cache_dir_bytes_growth": progress_cache_dir_bytes_growth,
                            "polled_at": polled_at,
                        },
                        ensure_ascii=True,
                    ),
                    flush=True,
                )
                last_report_monotonic = now_monotonic
            if (
                min_stable_progress_samples is not None
                and stable_progress_sample_count >= min_stable_progress_samples
                and not kill_requested
                and not (isinstance(status, str) and status in TERMINAL_STATUSES)
            ):
                kill_payload = _worker_kill(worker_base_url, backtest_id)
                stop_rule_summary = {
                    "reason": "min_stable_progress_samples_reached",
                    "min_stable_progress_samples": min_stable_progress_samples,
                    "stable_progress_sample_count": stable_progress_sample_count,
                    "requested_at": polled_at,
                    "kill_response": kill_payload,
                }
                kill_requested = True
                print(
                    json.dumps(
                        {
                            "event": "stop_rule_reached",
                            "backtest_id": backtest_id,
                            "stable_progress_sample_count": stable_progress_sample_count,
                            "min_stable_progress_samples": min_stable_progress_samples,
                            "kill_status": kill_payload.get("status"),
                            "polled_at": polled_at,
                        },
                        ensure_ascii=True,
                    ),
                    flush=True,
                )
            if point is not None:
                previous_point = point
            if isinstance(status, str) and status in TERMINAL_STATUSES:
                final_progress = progress_payload if isinstance(progress_payload, dict) else {"progress": None}
                return status_payload, final_progress, rows, stop_rule_summary
            time.sleep(poll_seconds)


def _total_seconds(started_at: str | None, finished_at: str | None) -> float | None:
    if not started_at or not finished_at:
        return None
    try:
        start = _parse_iso8601_loose(started_at)
        end = _parse_iso8601_loose(finished_at)
        return round((end - start).total_seconds(), 3)
    except Exception:
        return None


def run_serial_harness(args: argparse.Namespace) -> dict[str, Any]:
    harness_dir = Path(args.harness_dir).expanduser().resolve()
    results_dir = Path(args.results_dir).expanduser().resolve()
    results_dir.mkdir(parents=True, exist_ok=True)
    modes = _mode_order(args.modes)
    cache_stats_ssh_target = args.cache_stats_ssh_target or args.reset_ssh_target

    config = {
        "harness_dir": str(harness_dir),
        "worker_base_url": args.worker_base_url,
        "results_dir": str(results_dir),
        "modes": modes,
        "poll_seconds": args.poll_seconds,
        "skip_initial_chunks": args.skip_initial_chunks,
        "cache_stats_ssh_target": cache_stats_ssh_target,
        "reset_ssh_target": args.reset_ssh_target,
        "cache_dir": args.cache_dir,
        "drop_page_cache": bool(args.drop_page_cache),
        "require_idle_worker": bool(args.require_idle_worker),
        "min_stable_progress_samples": args.min_stable_progress_samples,
    }
    (results_dir / "config.json").write_text(json.dumps(config, ensure_ascii=True, indent=2) + "\n", encoding="utf-8")

    summaries: list[dict[str, Any]] = []
    for mode in modes:
        mode_dir = results_dir / mode
        mode_dir.mkdir(parents=True, exist_ok=True)
        print(json.dumps({"event": "mode_start", "mode": mode}, ensure_ascii=True), flush=True)

        if args.require_idle_worker:
            active = _active_run_count(args.worker_base_url)
            if active != 0:
                raise RuntimeError(f"worker is not idle before {mode}: active_count={active}")

        reset_summary = None
        if args.reset_ssh_target:
            reset_summary = _reset_worker_cache(
                ssh_target=args.reset_ssh_target,
                cache_dir=args.cache_dir,
                drop_page_cache=bool(args.drop_page_cache),
            )
            print(
                json.dumps(
                    {
                        "event": "cache_reset",
                        "mode": mode,
                        "ssh_target": args.reset_ssh_target,
                        "cache_dir": args.cache_dir,
                        "drop_page_cache": bool(args.drop_page_cache),
                    },
                    ensure_ascii=True,
                ),
                flush=True,
            )
            (mode_dir / "cache_reset.json").write_text(
                json.dumps(reset_summary, ensure_ascii=True, indent=2) + "\n",
                encoding="utf-8",
            )

        backtest_id = _make_backtest_id(mode)
        cache_stats_before_submit = (
            _sample_worker_cache_stats(
                ssh_target=cache_stats_ssh_target,
                cache_dir=args.cache_dir,
            )
            if cache_stats_ssh_target
            else None
        )
        run_spec, bundle_name, bundle_bytes, runner_bytes, runner_support_bundle_bytes = _load_submission_assets(
            harness_dir,
            mode,
            backtest_id,
        )
        run_spec_bytes = (json.dumps(run_spec, ensure_ascii=True, indent=2) + "\n").encode("utf-8")
        (mode_dir / "submitted_run_spec.json").write_bytes(run_spec_bytes)

        run_id = _submit_to_worker(
            worker_base_url=args.worker_base_url,
            backtest_id=backtest_id,
            run_spec_bytes=run_spec_bytes,
            bundle_name=bundle_name,
            bundle_bytes=bundle_bytes,
            runner_bytes=runner_bytes,
            runner_support_bundle_bytes=runner_support_bundle_bytes,
        )
        print(
            json.dumps(
                {
                    "event": "submitted",
                    "mode": mode,
                    "backtest_id": backtest_id,
                    "run_id": run_id,
                    "worker_base_url": args.worker_base_url,
                },
                ensure_ascii=True,
            ),
            flush=True,
        )

        final_status, final_progress, progress_rows, stop_rule_summary = _poll_until_complete(
            worker_base_url=args.worker_base_url,
            backtest_id=backtest_id,
            poll_seconds=args.poll_seconds,
            progress_log_path=mode_dir / "progress.jsonl",
            skip_initial_chunks=args.skip_initial_chunks,
            min_stable_progress_samples=args.min_stable_progress_samples,
            cache_stats_ssh_target=cache_stats_ssh_target,
            cache_dir=args.cache_dir,
        )
        log_text = _worker_logs(args.worker_base_url, backtest_id)
        cache_stats_after_run = (
            _sample_worker_cache_stats(
                ssh_target=cache_stats_ssh_target,
                cache_dir=args.cache_dir,
            )
            if cache_stats_ssh_target
            else None
        )
        (mode_dir / "worker.log").write_text(log_text, encoding="utf-8")
        (mode_dir / "final_status.json").write_text(
            json.dumps(final_status, ensure_ascii=True, indent=2) + "\n",
            encoding="utf-8",
        )
        (mode_dir / "final_progress.json").write_text(
            json.dumps(final_progress, ensure_ascii=True, indent=2) + "\n",
            encoding="utf-8",
        )

        progress_summary = summarize_progress_rows(
            progress_rows,
            skip_initial_chunks=args.skip_initial_chunks,
        )
        progress_payload = final_progress.get("progress")
        started_at = None
        finished_at = None
        if isinstance(progress_payload, dict):
            started_at = progress_payload.get("started_at")
            finished_at = progress_payload.get("finished_at")
        if not started_at:
            started_at = final_status.get("started_at")
        if not finished_at:
            finished_at = final_status.get("finished_at")

        summary = {
            "mode": mode,
            "backtest_id": backtest_id,
            "run_id": run_id,
            "worker_base_url": args.worker_base_url,
            "status": final_status.get("status"),
            "error": final_status.get("error"),
            "started_at": started_at,
            "finished_at": finished_at,
            "total_seconds": _total_seconds(started_at, finished_at),
            "warmup_lines": _extract_warmup_lines(log_text),
            "cache_reset": reset_summary,
            "cache_stats_before_submit": cache_stats_before_submit,
            "cache_stats_after_run": cache_stats_after_run,
            "stop_rule": stop_rule_summary,
            "progress_summary": progress_summary,
        }
        (mode_dir / "summary.json").write_text(
            json.dumps(summary, ensure_ascii=True, indent=2) + "\n",
            encoding="utf-8",
        )
        print(
            json.dumps(
                {
                    "event": "mode_complete",
                    "mode": mode,
                    "backtest_id": backtest_id,
                    "status": summary["status"],
                    "total_seconds": summary["total_seconds"],
                    "stable_events_per_second_median": summary["progress_summary"]["progress_events_per_second_median"],
                    "stable_simulated_seconds_per_wall_second_median": summary["progress_summary"]["progress_simulated_seconds_per_wall_second_median"],
                },
                ensure_ascii=True,
            ),
            flush=True,
        )
        summaries.append(summary)

    aggregate = {
        "generated_at": _utc_timestamp_id(),
        "worker_base_url": args.worker_base_url,
        "results_dir": str(results_dir),
        "modes": summaries,
    }
    (results_dir / "summary.json").write_text(
        json.dumps(aggregate, ensure_ascii=True, indent=2) + "\n",
        encoding="utf-8",
    )
    return aggregate


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    summary = run_serial_harness(args)
    print(json.dumps(summary, ensure_ascii=True, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
